### ISSUE TITLE
amazon-ssm-agent not working on Ubuntu Xenial (16.04 LTS)

### ISSUE THREAD

**Issue by TravellingGuy** [aws/amazon-ssm-agent#10]
The amazon-ssm-agent seems to rely on upstart to stop/start, but upstart is deprecated on Ubuntu 16.04 LTS (in favour of systemd).

**Comment by shihuazhang** [comment]
Hi TravellingGuy,
We are aware of the issue, the team is working on the fixes. 
Thanks for your comment

**Comment by vladgh** [comment]
Any update on this?

**Comment by shihuazhang** [comment]
SSM Agent 1.2.290.0 with Ubuntu 16 support is ready for download. 
https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/debian_amd64/amazon-ssm-agent.deb

Please give it a try and let us know if you encounter any issue.

**Comment by PeteLawrence** [comment]
@shihuazhang That link you give appears to be a previous version - 1.2.252.0.  The Last-Modified header returns 'Sat, 02 Jul 2016 02:25:18 GMT'

**Comment by shihuazhang** [comment]
@PeteLawrence My apologizes, the release hasn't been rolled-out to us-east-1 yet.

Please feel free to grab it from here.
https://s3.eu-central-1.amazonaws.com/amazon-ssm-eu-central-1/1.2.290.0/debian_amd64/amazon-ssm-agent.deb

**Comment by stephonchen** [comment]
@shihuazhang 
Thanks for patching this package.
But amazon-ssm-agent would not be auto started in Ubuntu 16.04 due to systemd not set up.
Would you like to patch post-{rm, install} command to achieve this?

Sample:
 # systemctl enable amazon-ssm-agent.service
 # systemctl start amazon-ssm-agent.service

Thanks a lot
