### ISSUE TITLE
Sophos UTM responding to link local http requests prevents managed instance registration

### ISSUE THREAD

**Issue by omenlabs** [aws/amazon-ssm-agent#134]
I found a weird corner case with setting up a managed instance on a network with a Sophos UTM of some kind.  The issue is that the UTM intercepts the HTTP request to 169.254.169.254 and returns a response.  I think this tricks the amazon-ssm-agent into thinking it is inside AWS.  The agent doesn't fall back to using the external API address for SSM registration and instead fails.

```
# curl http://169.254.169.254
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>The requested URL could not be retrieved</title>
    <link href="http://passthrough.fw-notify.net/static/default.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://passthrough.fw-notify.net/static/default.js"></script>
......
```

This results in the registration failing with a message of: 

```
2018-11-01 00:10:19 ERROR Registration failed due to error registering the instance with AWS SSM. ActivationExpired: 
	status code: 400, request id:
```

A workaround for this problem is to blackhole 169.254.169.254:

```
route add -host 169.254.169.254 reject
```

**Comment by AmyZhangAmz** [comment]
Thank you for posting here. Based on the message in the log, SSM agent is attempting to perform an on-premises activation, which is failing because the activation has expired. Activations have an expiration date set when they're created and are limited to a maximum duration of 30 days. In order to register on-premises instance successfully, you need create an activation and re-run the registration.

**Comment by omenlabs** [comment]
The reactivation was blocked because the firewall was responding to requests to 169.254.169.254
