### ISSUE TITLE
S3 files still created without the correct ACL bucket-owner-full-control

### ISSUE THREAD

**Issue by AmiSMB** [aws/amazon-ssm-agent#139]
Even with SSM Agent > 2.0.672 to the latest version we are still seeing that even with an S3 policy allowing PubObject and PutObjectAcl on the bucket, files are being uploaded but not having the ACL changed to bucket-owner-full-control. Looking at the code I would suggest that the ACL needs to be added to the s3manager.UploadInput rather than doing the upload and then applying the ACL.

**Comment by dimagermanov** [comment]
Thank you for request.

The way the code is currently written should also work when instance has s3:PutObjectAcl allowed in IAM policy.
Many user don't have PutObjectAcl allowed, and the existing logic will still upload files for them while gracefully failing to set ACL.
Are you sure IAM role has PutObjectAcl allowed for the bucket?

**Comment by AmiSMB** [comment]
Hi. I have a lambda function written in python that writes the files cross account in S3 and uses the putObject with acl 'bucket-owner-full-control' which works fine. SSM is using the same credentials cross account so I know the s3:PutObjectAcl is enabled.

**Comment by paritadhandha** [comment]
Thank you for posting the issue here. 
I tried reproducing the issue but I was not able to. Is it still the issue? If so could you please provide steps to reproduce the issue? E.g. The relevant role policies and trust relationships used in the role, bucket policy, how you are using ssm to upload to s3 (maybe run command) etc. Please make sure to remove or replace the account ids, bucket names, role names etc with dummy values. 
Thanks,
Parita

**Comment by shihuazhang** [comment]
issue addressed in 2.3.722.0
