### ISSUE TITLE
Unable to gain necessary access for possible kernel updates, code: 1.

### ISSUE THREAD

**Issue by zith5364** [aws/amazon-ssm-agent#185]
Hello,

I am trying to run AWS-runpatchbaseline on my Ec2-instances and i am doing install on my ec2-instances for latest instances.

My task is successful but when i go to logs , i found out below warning.

root [WARNING]: Unable to gain necessary access for possible kernel updates, code: 1.

**Comment by AmyZhangAmz** [comment]
Hi zith5364, 

You can safely ignore that warning, it's unrelated to this scenario. 
Is there any chance you could provide a bit more detail about what you're seeing? The complete output of the AWS-RunPatchBaseline would be helpful to troubleshoot this.

Thanks!

**Comment by LiangChiAmzn** [comment]
Hi zith5364,

We will be closing this issue as this log is generated by the Patch Manager service instead of the SSM Agent itself.

Please feel free to reach out to service teams on the AWS Systems Manager Discussion Forum if you still have questions:
https://forums.aws.amazon.com/forum.jspa?forumID=185

Thank you!

**Comment by mohankumar98** [comment]
> Hello,
> 
> I am trying to run AWS-runpatchbaseline on my Ec2-instances and i am doing install on my ec2-instances for latest instances.
> 
> My task is successful but when i go to logs , i found out below warning.
> 
> root [WARNING]: Unable to gain necessary access for possible kernel updates, code: 1.

**Comment by mohankumar98** [comment]
I get a same error
Can you give me solution for this error.

**Comment by younsl** [comment]
I got a same error, when I try to run AWS-RunPatchBaseline on Amazon Linux 2 EC2 via SSM Patch Manager.
Is there any solutions?

```bash
# Run Commands Output on AWS Management Console
...
10/17/2022 16:17:45 root [INFO]: Reboot Option: RebootIfNeeded
10/17/2022 16:17:45 root [WARNING]: Unable to gain necessary access for possible kernel updates, code: 1.
10/17/2022 16:17:45 root [INFO]: Loading patch snapshot from snapshot.json
...
```

the related AWS doc is [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-troubleshooting.html).

<img width="870" alt="image" src="https://user-images.githubusercontent.com/87736192/196231136-3c4b46e0-f631-49a3-8d76-f85f29a691c1.png">

But In my opinion,  The reason stated in the official document does not related to me.
Because python3 version on my ec2 is not a problem.

```bash
$ python3 --version
Python 3.7.10
```

**Comment by ghost** [comment]
You can break this down to the following PatchManager function in
patch-baseline-operations-1.108/common_os_selector_methods.py:

```
def _setup_se_linux_context():
    """
    When SE Linux is enabled, the installation script needs to be given the appropriate SE Linux context for it to
    install certain packages.
    Will swallow errors if it can't do it, since only some packages require the context change
    :return:
    """
    try:
        (chcon_path, returncode) = shell_interaction.shell_command(["which", "chcon"])
        if returncode != 0:
            logger.warn("Unable to locate chcon, code: %d.", returncode)
            return
        chcon_path = chcon_path.strip()

        (yum_path, returncode) = shell_interaction.shell_command(["which", "yum"])
        if returncode != 0:
            logger.warn("Unable to locate yum, code: %d.", returncode)
            return
        yum_path = yum_path.strip()

        (_, returncode) = shell_interaction.shell_command([chcon_path, "--reference", yum_path, "./main_entrance.py"])
        if returncode != 0:
            logger.warn("Unable to gain necessary access for possible kernel updates, code: %d.", returncode)
    except:
        # already tried to set SELinux access but failed, continue to update packages
        pass
```

So you'll get this warning if the chcon command fails, e.g. because SELinux is disabled. If that's the case you can ignore this warning.
