### ISSUE TITLE
Installation with snap on Ubuntu 18 (on-premise)

### ISSUE THREAD

**Issue by dorintt** [aws/amazon-ssm-agent#192]
AWS docs about installation state that on Ubuntu 18 the snap package should be used instead of deb.

Therefore I did `snap install amazon-ssm-agent --classic`, however upon inspecting the service I get the same errors as in this case https://github.com/aws/amazon-ssm-agent/issues/114

Moreover, snap installation seems to be even more broken than the .deb installation as `$ amazon-ssm-command` is not linked to anything and `/etc/amazom/etc` doesn't even exist. 

I have no clue how to proceed with registration because aws documentation only mentions installation and stops there.

**Comment by nanicpc** [comment]
same problem for me

**Comment by Zyles** [comment]
Fix?

**Comment by mikeg-de** [comment]
Same problem here too.

**Comment by Zyles** [comment]
Amazon are shit at documenting and their programmers are incapable of writing error messages that actually tell you what the problem is.

The solution I found is that you need to use the snap binary like this:

```
sudo /snap/amazon-ssm-agent/current/amazon-ssm-agent -register -code "activation-code" -id "activation-id" -region "region"
sudo systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service
sudo systemctl stop snap.amazon-ssm-agent.amazon-ssm-agent.service
```

The files that need to be in `/etc/amazon` will be generated after registration and the agent is launched, once you ran the wizard and started the agent.

**Comment by shihuazhang** [comment]
Thanks for your feedback, we are improving the documentation.
