### ISSUE TITLE
Snap packages update?

### ISSUE THREAD

**Issue by arnaudmm** [aws/amazon-ssm-agent#196]
Hello,

Is this possible to get last version 2.3.672.0 in snap repository?
Last published version is 2.3.662 : https://snapcraft.io/amazon-ssm-agent

Thanks!

**Comment by paritadhandha** [comment]
Hello arnaudmm,

You can find the latest version of amazon-ssm-agent on the [candidate](https://docs.snapcraft.io/getting-started) channel of snap. 

The agent version that gets published to github, also gets published to the candidate channel of snap.
1. You can install the latest agent from the candidate channel using
```
sudo snap install --channel=candidate amazon-ssm-agent --classic
```
2. Since the snaps get refreshed periodically, you can also consider changing the channel from which the agent gets refreshed using following command.
```
sudo snap switch --channel=candidate amazon-ssm-agent
```
Then you can manually perform refresh or wait for the auto refresh.
```
sudo snap refresh amazon-ssm-agent
```
Thanks!

**Comment by arnaudmm** [comment]
Great thank you @paritadhandha

**Comment by paritadhandha** [comment]
I hope that helped. Closing this issue. Feel free to open this or another issue if you need.
Thanks!

**Comment by acdha** [comment]
Is there an ETA for that going into the stable release? I was surprised that the SSH support didn't work until I noticed that the automatic updates were three releases behind.
