### ISSUE TITLE
Confusing error messages for State Manager running AWS-UpdateSSMAgent

### ISSUE THREAD

**Issue by udhos** [aws/amazon-ssm-agent#199]
I am seeing two confusing errors for the same Run document AWS-UpdateSSMAgent invoked from State Manager:

1. On some instances, I get the unexpected error below. Is it correct to throw this as a DOWNGRADE ERROR, since the version is actually the last one and should be kept unchanged? Shouldn't it report simply a skip/success?

```
Updating amazon-ssm-agent from 2.3.680.0 to latest

Successfully downloaded https://s3.sa-east-1.amazonaws.com/amazon-ssm-sa-east-1/ssm-agent-manifest.json

----------ERROR-------

updating amazon-ssm-agent to an older version, please enable allow downgrade to proceed
```

2.  On other instances, there is the unexpected error below. Why wasn't the agent simply updated to the actual latest version 2.3.680.0 ?

```
Updating amazon-ssm-agent from 2.3.672.0 to latest

Successfully downloaded https://s3.sa-east-1.amazonaws.com/amazon-ssm-sa-east-1/ssm-agent-manifest.json

amazon-ssm-agent 2.3.672.0 has already been installed, update skipped
```

**Comment by paritadhandha** [comment]
Hello udhos,

The current agent release process is regional so there might be difference of agent versions in global and regional buckets. The AWS-UpdateSSMAgent document always uses the regional bucket to get the agent. So if for example you installed the agent from the global bucket which has 2.3.680.0 version as the latest one. And then you use the document to update it, the document referred to the regional bucket which may have version 2.3.672.0 as the latest. Therefore it'd ask you to "enable allow downgrade to proceed
". 

This could also explain the error in your second case, where the instance has 2.3.672.0 version of the agent installed and when the document tried to update it, it referred to the regional bucket and skipped the update to the latest because it's already installed. 

You can also refer to the **Note** given under **Keeping SSM Agent up-to-date**: https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html

Feel free to re-open the issue if you have any more issues.

Thanks,
Parita

**Comment by VolkerK** [comment]
I just had a similar problem.
When creating an ec2 instance, in the UserData I install the latest version of ssm agent with 
`yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm`.

Then later, my MaintenanceWindow uses the standard document `AWS-UpdateSSMAgent` and I get the error:
`Updating amazon-ssm-agent from 2.3.707.0 to latest
Successfully downloaded https://s3.us-east-1.amazonaws.com/amazon-ssm-us-east-1/ssm-agent-manifest.json
----------ERROR-------
updating amazon-ssm-agent to an older version, please enable allow downgrade to proceed
`
I guess the problem is that the rpm has a newer version then the AWS-UpdateSSMAgent document.

**Comment by petersonpeter** [comment]
I am getting the same error as well when running the document in the ap-south-1 region.
