### ISSUE TITLE
Please update the stable snap package

### ISSUE THREAD

**Issue by abeluck** [aws/amazon-ssm-agent#213]
In the spirit of those [gone](https://github.com/aws/amazon-ssm-agent/issues/129) [before](https://github.com/aws/amazon-ssm-agent/issues/196)...

...please update the stable channel of amazon-ssm-agent.

**Comment by paritadhandha** [comment]
It would be great if you could tell us what features you are specifically looking for in the agent or the agent version. 
In the mean time, you can get the latest agent from the candidate channel for the agent.
Thanks,
Parita

**Comment by kchristensen** [comment]
We're after a version that supports the SSH functionality, so we can use it instead of native SSH when building AMIs.

**Comment by abeluck** [comment]
SSH and port forwarding for us as well

**Comment by acdha** [comment]
@paritadhandha SSH and port forwarding were what made me start tracking this issue but in general it'd be nice to have some sort of policy so we'd be able to know how long things take to make it from a GitHub release to the various snap channels — e.g. 2.3.714 was released yesterday, the snap candidate channel has 2.3.707 and stable is 2.3.672. It'd be nice to have some sort of policy (e.g. “Candidate updates n days after a release, stable updates n weeks after the candidate”) so we could know how long it'll take between something being fixed in Git and actually  fixed on our servers.

**Comment by LiangChiAmzn** [comment]
Thank you for reaching out to us.

The `candidate` channel in Snap is now in line with the latest build of SSM Agent (2.3.714). We do our best to keep the `candidate` channel with the newest features and fixes, it should take no more than a week for the `candidate` channel to be updated. As for the `stable` channel, we usually leave several weeks of bake time before promoting a version from `candidate` to `stable` channel, but there is not a clearly defined schedule at this moment.

Hope this helps!

**Comment by awiddersheim** [comment]
FYI, the stable [snap](https://snapcraft.io/amazon-ssm-agent) package has been updated to `2.3.672.0` which is the earliest version that supports `SSH` and port forwarding.
