### ISSUE TITLE
Unable to start a new session as ssm-user with runAS option

### ISSUE THREAD

**Issue by ppieprzycki** [aws/amazon-ssm-agent#217]
Without "run as" option the "ssm-user"  is created during the first session.  If I configure SSM and set "run as" and as default user use "ssm-user" I'm unable to login into new vm's. 
I get an error "Unable to start shell: failed to start pty since RunAs user ssm-user does not exist"

Please let me know if such as PR will resolve this issue 
https://github.com/ppieprzycki/amazon-ssm-agent/commit/0964467ada738e855fd6f41a15a1ac928aed3186

Regards
Piotr Pieprzycki

**Comment by sumohite** [comment]
Thank you for reaching out. Which version of the agent are you using? Could you try updating it to the latest version?

**Comment by tcharewicz** [comment]
Hello,

You can reproduce this problem by running ec2 from Ubuntu 18.04 AMI ( The agent is in version 2.3.672.0 ). I have updated this agent to the latest version, 2.3.758.0, and the problem persists.

--
regards
TomekC

**Comment by sruthi-maddineni** [comment]
To use runAs with session manager, the username specified has to be an existing user. Agent will not attempt to create the user when runAs is enabled. Let us know if you have any other questions.

**Comment by tcharewicz** [comment]
If I understand correctly that I am using the default user for SSM, which I cannot use after starting the instance. It's weird. It's a security feature? For what?

**Comment by Wenzil** [comment]
@sruthi-maddineni Would it be possible in the future to allow that runAs user to be created automatically?

Any recommendations otherwise on how to automate the creation of OS users corresponding to the list of IAM users with permission to start sessions on a given set of instances? I am new to SSM so sorry if this is obvious!

**Comment by nitikaaws** [comment]
Thanks for your feedback! Session Manager do not support automatic creation of configured Run As user and this user creation should be handled separately before staring a session. Let us know in case of further queries.

**Comment by gurpalw** [comment]
But why doesn't it support it?

It seems a bit strange that it will create the `ssm-user` when Run As is disabled, but if it is enabled, and the role attempting to connect has the tag to use the user `ssm-user` that it won't create the user.

Seems odd.

My use case:

Have some users tagged with `SSMSessionRunAs = "ssm-user"` so that they have root permissions when they create a session. We want this because only certain people should have root access via ssm.

If the user is not tagged with that, then connect with the (non root) user defined in the "General Preferences" of the Session Manager in the aws console.

**Comment by carterwilliamson** [comment]
Any chance this will get reviewed? It's a totally valid use case and frankly poor design. It seems at least we could have an option for "create user at first session".
There's a number of issues related to this and they all are closed with the reason "that's how it works" with no supporting arguments as to _why_. Please provide an explanation as to why this is/cannot be supported.

**Comment by alwatt** [comment]
bump

**Comment by akulihin** [comment]
The workaround for this is to create "ssm-user" yourself in the cloud-init script.
Add the following code to your cloud-init script:
```
# Creating ssm-user user
sudo useradd -m ssm-user -s /bin/sh;
sudo passwd --delete ssm-user;

#Allow ssm-user user to be root
sudo echo "ssm-user ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/ssm-agent-users;
```

If you are using terraform this would be in your "user_data_base64"
