### ISSUE TITLE
Session Manager does not work if root volume is full

### ISSUE THREAD

**Issue by JeremiahO1** [aws/amazon-ssm-agent#225]
Session manager won't connect to instances when the root volume is full. This is one of the main reasons I find needing to get into an instance so would be nice if there was a way to bypass this limitation.

**Comment by shihuazhang** [comment]
Thanks for your interest about amazon ssm agent. 

SSM Agent requires disk space to be able to function normally.

**Comment by JeremiahO1** [comment]
Could there be a modification for the SSM agent to put the files in a non-root volume? like /dev/shm or something else? this would ensure that even when `/` is full, there is a small partition ssm could mount its files to.

**Comment by shihuazhang** [comment]
Thanks for your feedback, we’ll work on this feature request.

**Comment by krazykelv** [comment]
Is this being worked on?  This is an issue for us as well

**Comment by iancward** [comment]
See related #170

**Comment by asyschikov** [comment]
@shihuazhang this is a very important feature. I had an EC2 instance that I used SSM to connect to. It had no SSH keys, was located in a private subnet. It ran out of space and it got essentially "bricked" because SSM stopped working. SSM is a critical connectivity tool and an instance becoming unaccessible for no good reason is a huge risk.
