### ISSUE TITLE
Ubuntu 18.04 on premise

### ISSUE THREAD

**Issue by Zyles** [aws/amazon-ssm-agent#247]
Does this thing work?

Ubuntu 18.04 on premise
Installed using snap --classic
Configured credentials using aws cli --configure
```
Failed to load instance info from vault. RegistrationKey does not exist.
INFO Entering SSM Agent hibernate - Failed to fetch instance ID. Data from vault is empty. RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/instance-id: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
Instance does not show up in SSM.

![image](https://user-images.githubusercontent.com/1741593/71301055-135d3500-239b-11ea-9412-83ec356b5b91.png)

What else needs to be done?

**Comment by LiangChiAmzn** [comment]
Hello Zyles,

Thank you for reaching out to us. Yes, SSM does support Ubuntu 18.04 platform as of today, but the Agent does not retrieve the credential from AWS CLI. In order to use SSM on hybrid environments, you need to first create an `Activation`, then use the `Activation Code` and `Activation ID` to register the host as a managed instance under SSM.

Please refer to this documentation for detailed instructions:
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-install-managed-linux.html

Thanks!
