### ISSUE TITLE
When `Run As` is enabled and starting session from Role, SSM returns 500 Internal Error

### ISSUE THREAD

**Issue by Klohto** [aws/amazon-ssm-agent#263]
I'm unable to start a new session from Console.
Endpoint `https://eu-west-1.console.aws.amazon.com/systems-manager/api/ssm` always returns 500 with following error:
`com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Message" (class com.amazonaws.messagegatewayservice.exception.BadRequest), not marked as ignorable (3 known properties: "cause", "clientErrorMessage", "stackTrace"]) at [Source: (StringReader); line: 2, column: 162] (through reference chain: com.amazonaws.messagegatewayservice.exception.BadRequest["Message"])`

To make it less complicated, I'm starting new session from Role that has `SSMSessionRunAs` tag correctly created, with value `ssm-user`. If I define default user in `Run As` settings as `ssm-user`, I get the same error. There is no indication of connection in SSM agent logs on the desired machine.
If I disable `Run As`, everything works.

Testing the same configuration with a User works, although SSM logs `Encountered error while initiating handshake. Handshake timed out`. But that I believe is unrelated and is a problem with my configuration.

**Comment by nitikagoyal87** [comment]
Thanks for reaching out!
We are unable to replicate this issue using switch role from AWS Console. Could you please help us with below information to root cause this further:
- How did you use IAM role to login to console among various options provided in public documentation https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html? 
- Will you be able to try switch role from IAM Console to see if Session Manager with RunAs works for you?
- A sample session id for which 500 error was thrown
