### ISSUE TITLE
Can files in /var/log/amazon/ssm/download be removed safely?

### ISSUE THREAD

**Issue by michaelsmoody** [aws/amazon-ssm-agent#309]
I've left my thoughts about the improperness of this download location in https://github.com/aws/amazon-ssm-agent/issues/88. However, assuming for a moment that the location doesn't change, can the files be removed safely?

If they can be removed safely, and if the download location isn't changed (or made configurable), can we add this to documentation, perhaps the README? Even better, could the solution be configured to remove old downloads, or only retain x old versions?

While it seems trivial, for systems where we have provisioned IOPS, or long term backup strategies, having these files around (a few hundred megs to a few gigs) can create a very real cost when you have thousands of instances, on the order of thousands of dollars extra each month. We can easily cost optimize for actual log files and our rotational strategies for those, but being unsure of these files and how they should be handled can add up.

Thanks,
Michael

**Comment by gianni-leslie** [comment]
Hi Michael,

You can delete those files, just make sure to stop the agent first to be extra sure the agent isn't in the middle of a process using the contents. Otherwise, the agent will re-download the resources it needs. We will add the automation of cleaning up those files when they are no longer needed to our backlog and reconsider our placement of the download folder. Thanks for bringing this to our attention.

-Gianni

**Comment by gianniLesl** [comment]
Hi Michael,
You can delete those files, just make sure to stop the agent first to be extra sure the agent isn't in the middle of a process using the contents. Otherwise, the agent will re-download the resources it needs. We will add the automation of cleaning up those files when they are no longer needed to our backlog and reconsider our placement of the download folder. Thanks for bringing this to our attention.
-Gianni

**Comment by pandafox** [comment]
Our server actually ran out of disk space due to the accumulation of the download file from SSM download folders
```
[0] ✓ ubuntu@ip-10-0-0-186:/var/log/amazon/ssm/download/update [02:37:19]
---> du -h
906M    .
```

**Comment by ykostsik** [comment]
Confirm, that the issue is still here.
499M	/var/log/amazon/ssm/download/update/

**Comment by ggarcia-trimble** [comment]
Does this got fixed?
