### ISSUE TITLE
AWS system manager RUN command getting timeout

### ISSUE THREAD

**Issue by gowthamakanthan** [aws/amazon-ssm-agent#332]
Team,

I've created role with SSMFullaccess and assigned the same to the newly created amazon linux 2 instances (Where the SSM agent is running and able to ssh). Afterwards, When I try to execute Run command, it's kept throwing the "Timeout" Error.

The instance is in private subnets(running in us-east-1) necessary VPC endpoints are in place. Also, port 80 is opened for the Instance SG. Any suggestions?
![image](https://user-images.githubusercontent.com/4055982/101328571-1715f000-3868-11eb-9df0-1657c2e9d63e.png)

**Comment by VishnuKarthikRavindran** [comment]
Hi @gowthamakanthan, 

Could you please let us know which SSM agent version you are working on?

**Comment by gowthamakanthan** [comment]
@VishnuKarthikRavindran, Apologies for the late reply. Am using ```3.0.161.0``` version.

**Comment by VishnuKarthikRavindran** [comment]
Sorry for the late reply @gowthamakanthan. Could you please check whether the issue still persists with the latest agent version? If not, could you please open a support ticket in AWS Console and attach the full error.log and amazon-ssm-agent.log to assist us in finding the root cause?

https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-agent-logs.html
https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case
