### ISSUE TITLE
Feature Request: Releases Should Contain Precompiled Binaries

### ISSUE THREAD

**Issue by osterman** [aws/amazon-ssm-agent#50]
## what
* Each release should attach the precompiled binaries here: https://github.com/aws/amazon-ssm-agent/releases

## example
* https://github.com/cloudposse/github-authorized-keys/releases

## why
* Facilitate distribution on non-debian distributions

## how to
* this is very easy to accomplish with travis. Here's an example: 
   https://github.com/cloudposse/github-authorized-keys/blob/master/.travis.yml#L51
   https://github.com/cloudposse/sudosh/blob/master/.travis.yml#L24

**Comment by mmendonca3** [comment]
Thank you for your request. I will forward your request to the appropriate team.

**Comment by mmendonca3** [comment]
Hello osterman, 

The team currently does not have plans to add the precompiled binaries to GitHub releases. 

If you need to access the precompiled binaries, we already have them listed here - https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html. 

I will be closing this request. Please feel free to reopen it if you have any other questions.

**Comment by remil1000** [comment]
Hi,

would you consider the release of precompiled binaries so that we could use ssm-agent without going through the process of extracting the executables from the AWS maintained `rpm` or `deb` packages ?

I've tested some basic integration with Github actions and matrix build to push a subset of binaries to Github releases but I obviously be happier if this was integrated upstream

For example
https://github.com/remil1000/amazon-ssm-agent/releases/tag/3.2.183.0-gh2

with the following change set/commit
https://github.com/aws/amazon-ssm-agent/commit/bf9975715948a2edd370bf11474e29e48f6a94ac
