### ISSUE TITLE
Windows Server 2025 Compatibility

### ISSUE THREAD

**Issue by djcampbell** [aws/amazon-ssm-agent#597]
When can we expect a release compatible with Windows Server 2025? SSM agent upgrades fail due to the deprecation of wmic.exe in 2025.

Error from running document: AWS-UpdateSSMAgent in State Manager:

Failed to create update info object: exec: "wmic": executable file not found in %PATH%

**Comment by Aperocky** [comment]
We are actively working on compatibility with Windows 2025 and moving away from `wmic` as it is deprecated in Windows 2025.

For now, you can resolve this via SSM by running command document `AWS-RunPowerShellScript` with this as content:

     Add-WindowsCapability -Online -Name "WMIC"
 
 And after this successfully execute, both Session and UpdateSSMAgent should work.

---

Edit: The latest release `3.3.1345.0` should fix this issue. If you currently have an older version on an existing 2025 machine, you may still need to conduct mitigating steps in order to upgrade to it.

**Comment by djcampbell** [comment]
Thanks Rocky. I found the DISM command to enable wmic after posting this issue. I've implemented the workaround into our images.

**Comment by benjaminejarrell** [comment]
Updating to the latest release fixed this for me. https://github.com/aws/amazon-ssm-agent/releases/tag/3.3.1311.0

**Comment by Aperocky** [comment]
Agent version `3.3.1345.0` supports Windows 2025.
