### ISSUE TITLE
Ability to customise DefaultDocumentWorker

### ISSUE THREAD

**Issue by c-knowles** [aws/amazon-ssm-agent#76]
Is it possible to customise the value for `DefaultDocumentWorker` on linux?

By default it appears to be hard coded to `/usr/bin`:
https://github.com/aws/amazon-ssm-agent/blob/e092980b261c432156f738dc1531666bf8277679/agent/appconfig/constants_unix.go#L79 

We're trying to deploy on Container Linux based on [this blog post](https://medium.com/levops/how-to-work-with-aws-simple-system-manager-on-coreos-4741853dfd50). It's not a current supported OS, although the agent does work fine if we rebuild after changing that value. The reason it needs to be different is on Container Linux `/usr` is read only to allow for OS updates.

**Comment by shengmiw** [comment]
we currently don't support customizing binary paths.

**Comment by hui-yang** [comment]
I have the same request for a different use case.
I simply compiled amazon-ssm-agent from source on an unsupported OS, and I had to move `ssm-document-worker` binary from build directory to `/usr/bin`, because the reference is hardcoded.

Do you support this use case?
If yes, the Readme should mention it https://github.com/aws/amazon-ssm-agent#building-and-running-from-source 
If not, do you suggested always create a release package?

**Comment by jhmartin** [comment]
Same issue here; realizing CoreOS is not a supported OS but the hardcoding is unnecessarily strict.

**Comment by jhmartin** [comment]
FYI the last release before the worker process entered was https://github.com/aws/amazon-ssm-agent/releases/tag/2.0.952.0.

https://amazon-ssm-us-east-1.s3.amazonaws.com/2.0.952.0/linux_amd64/amazon-ssm-agent.rpm

**Comment by jpadilla** [comment]
Just ran into this as well. Any workarounds?

**Comment by c-knowles** [comment]
@jpadilla for what it's worth, we augmented the script from the blog post I linked above with this:

```bash
sed -i "s+/usr/bin/ssm-document-worker+$BIN_DIR/ssm-document-worker+g" agent/appconfig/constants_unix.go
```

That's not to say all agent actions work as the OS is still not supported, but at least now it runs and shell script can be executed and audited via SSM.

**Comment by jhmartin** [comment]
A custom build is certainly an option, but it is so much cleaner if it is a native configurable.

**Comment by jinal--shah** [comment]
@jpadilla @jhmartin @hui-yang - I've got a fork which lets you set $SSM_DOCUMENT_WORKER_PATH at agent **run**-time: https://github.com/opsgang/amazon-ssm-agent/

Effectively you can install the agent and ssm doc worker binaries anywhere.

You can download the built releases (these work on CoreOS amongst other linux amd4s) from here:
https://github.com/opsgang/amazon-ssm-agent/releases

I will be keeping this in-sync with the upstream - release builds are automated.

Hope its of use ...

**Comment by jhmartin** [comment]
@jinal--shah I suggest submitting a PR here with that, if nothing else AWS then can't complain about the work necessary to enable it.

**Comment by CrazySherman** [comment]
@jhmartin hardcoding path is not unnecessarily strict, aside from binary path we need to test additional requirements on CoreOS, which is currently unsupported. fork and put up your own build as @jinal--shah is a good way to try out. But again before we officially support CoreOS we didn't see good justification on make the document worker binary configurable. 
also plz note that having customers alter private binary path can risk losing track of update during the automated update process (package repository refresh or RunCommand), so for official release we need to make sure e2e support for a particular platform&OS rather than tweaking a specific binary path.

**Comment by mumoshu** [comment]
`DefaultDocumentWorker` is a var and I suppose it is ok to be modified at runtime.
It is handling [ubuntu w/ snap in that way](https://github.com/aws/amazon-ssm-agent/blob/a29d252ca05e278006d64402e79b6ec0c46a78eb/agent/appconfig/constants_unix.go#L108-L114).

**Comment by mumoshu** [comment]
@c-knowles @jpadilla @jhmartin Just submitted #101 for this. Would it work for you guys?

@jinal--shah's I was able to notice that it was just a matter of adding 4 lines today, thanks to the last commit in your fork. Thanks for that 🙏

**Comment by hiimtu** [comment]
Should be resolved: https://github.com/aws/amazon-ssm-agent/commit/bc7e78017a7802854fb9ddf313ca053a20e6a471
