### ISSUE TITLE
Feasibility Study to Determine Network Utilization Requirements for Hybrid Deployments

### ISSUE THREAD

**Issue by vbcodep** [aws/amazon-ssm-agent#80]
Doing feasibility study on deploying SSM agents on embedded remote devices  using metered Internet connections  running over cell modems and low speed licensed spectrum.    Polling latency would be acceptable in this scenario and could be parameterized. 

Will be setting up some tests over the next couple of weeks to analyze network traffic to end point and will be happy to publish results if this information is not available. 

Trying to determine how amazon endpoint is polled and how often.       Where would I find the endpoint polling in the code?

**Comment by thedevopsmachine** [comment]
In the directory in which the binaries reside you can copy the seelog.xml.template file to seelog.xml and change the log levels to debug instead of info. The debug logs show the polling activity.

To save you some time, it does a long poll every 20 seconds, receives a response, and starts a new long poll.

Request body:
{
  Destination: "mi-xxxxxxxxxxxxxxxxx",
  MessagesRequestId: "64a35511-e27a-4214-86c1-5a678f35db62",
  VisibilityTimeoutInSeconds: 10
}

Response body (after 20 seconds and not having received a job):
{
  Destination: "mi-xxxxxxxxxxxxxxxxx",
  Messages: [],
  MessagesRequestId: "64a35511-e27a-4214-86c1-5a678f35db62"
}

**Comment by mmendonca3** [comment]
Hello vbcodep, 

The agent polls the endpoint every 20 seconds. 

You can find this code in the scheduler - https://github.com/aws/amazon-ssm-agent/blob/master/agent/runcommand/scheduler.go. 

I am closing this issue. Please reopen it if you have any further questions.
